CREATE TABLE [HumanResources].[Employee] (
    [BusinessEntityID] INT           NOT NULL,
    [NationalIDNumber] NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [JobTitle]         NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [BirthDate]        DATE          NOT NULL,
    [MaritalStatus]    NCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Gender]           NCHAR (1)     COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [HireDate]         DATE          NOT NULL,
    [SalariedFlag]     BIT           NOT NULL,
    [VacationHours]    SMALLINT      NOT NULL,
    [SickLeaveHours]   SMALLINT      NOT NULL,
    [CurrentFlag]      BIT           NOT NULL,
    [ModifiedDate]     DATETIME      NOT NULL,
    CONSTRAINT [PK_Employee_BusinessEntityID] PRIMARY KEY CLUSTERED ([BusinessEntityID] ASC),
);