CREATE ROLE [DTSModifyRole] AUTHORIZATION [dbo];
GO
ALTER ROLE [DTSModifyRole] ADD MEMBER [BUILTIN\Users];
GO
CREATE ROLE [DTSReadRole] AUTHORIZATION [dbo];
GO
ALTER ROLE [DTSReadRole] ADD MEMBER [BUILTIN\Users];
GO
ALTER ROLE [DTSReadRole] ADD MEMBER [DTSModifyRole];
GO
CREATE ROLE [VisitorRole] AUTHORIZATION [dbo];
GO
ALTER ROLE [VisitorRole] ADD MEMBER [BUILTIN\Users];
GO